services:
  - type: web
    name: govt-schemes-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    repo: https://github.com/yourusername/govt-schemes-chatbot
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false  # Set manually in Render dashboard
      - key: FRONTEND_URL
        sync: false  # Set manually in Render dashboard